### ISSUE TITLE
severe weather mode bug

### ISSUE THREAD

**Issue by brenden7158** [buffbears/Weatherscan#23] opened 2022-08-09 19:14 UTC
![image](https://user-images.githubusercontent.com/38764606/183742550-e44de1a7-e9b1-46c6-b3eb-7b61ceee75d9.png)

**Comment by Galaga81** [comment] 2022-08-09 22:25
This was also mentioned in #15

**Comment by Galaga81** [comment] 2022-08-10 22:51
I think I have the fix for this. In slides-loop.js add this line:
$('.severe-city-info-slide').fadeOut(0);
right before the "//fade in" comment  around line 77

**Comment by Galaga81** [comment] 2022-08-10 23:09
Also, could we make
.bulletin #subhead-noaa {
font-size: 22px; (instead of 22.5px?). It's a bit tight in Safari.
![Screen Shot 2022-08-10 at 7 03 45 PM](https://user-images.githubusercontent.com/110785484/184038291-2a99e17a-3993-4483-b449-7fd35f4c4416.png)

**Comment by buffbears** [comment] 2022-08-11 01:06
The issue is is it's perfect in chrome. Ill fix the fade out issue.

**Comment by buffbears** [comment] 2022-08-11 02:05
Fixed.

**Closed as completed by buffbears** 2022-08-11 02:05 UTC
Labels: bug
